### ISSUE TITLE
Feature suggestion: counter for state types

### ISSUE THREAD

**Issue by roflmao** [bokub/ha-history-stats#2]
A suggestion for a counter type for historical stats;

on/off  - how many times have my washing machine been turned on (aka how many washes have i done the last month ex)
not_home/home - how many times have i left/entered the home
open/closed - how many times have the door been closed/opened

The config syntax could be similiar:
```
sensor:
  - platform: history_stats
    type: count
    name: Washing machine on count last 7 days
    entity_id: sensor.washing_machine
    state: 'on'
    start: {{ datetime.utcnow() - timedelta(days=7) }} #didnt get this syntax 100%
    end: {{ as_timestamp(now()) }}
```
